### ISSUE TITLE
French "learn mode" treats accented characters as word boundary.

### ISSUE THREAD

**Issue by brianyee0** [gospelcoding/biblehead-react-native#2]
When clicking the "double right arrow" to turn words into blanks, the words are broken at accented characters.

See: https://photos.google.com/share/AF1QipMWvJcw7m79-JtpwCapJIZN0b8jwm6jSr4K2SWnFTqB0IgJCObHwADGrPOVcBSmqw/photo/AF1QipMGo7Wid1a6nA6_vxRXXsA5Sp4shFChE-8k8WZE?key=NElCODVPZVlHOFcxOG9KelB4SnowVTRWNmFPZEJn

**Comment by rjconrad** [comment]
Fixed: https://github.com/gospelcoding/biblehead-react-native/commit/b56192f89a2c8b76d943a234f92c99f70936890e
